#spring.application.name=security

spring:
  datasource:
    url: jdbc:mysql://192.168.0.85:3306/smartteller_multitenancy
    username: root
    password: mysql
    #driver-class-name: org.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
   servlet:
     context-path: /smartteller_multitenancy

   #application:
     #security:
       #jwt:
        # secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
       #  expiration: 86400000 # a day
      #   refresh-token:
      #    expiration: 604800000 # 7 days
jwt:
  tokenExpiration: 120000000
  secretKey: K8dfUKdsfhadshj9001X;
  endpoints-using-temp-token: /validateOtp, /changePassword, /resetPassword
otp:
  requireOtp: false
  otpExpiryPeriod: 120
  otpMaxRetries: 3
